### ISSUE TITLE
Feature Request: Also for image search.

### ISSUE THREAD

**Issue by Lalarian** [wildskyf/personal-blocklist#11]
Hello!

Yes, I wanted to ask if it would be possible for you to also make this addon work for google image searches, so I can block images from Pinterest for example?

Thank you for attention! :)

**Comment by wildskyf** [comment]
sounds good, I will try it.

**Comment by Lalarian** [comment]
Sounds great!

**Comment by wildskyf** [comment]
merge into #15 
(I plan to try to implement this feature in the near future. Thanks for your patient!! )

**Comment by Lalarian** [comment]
No, I thank you (very much) for your effort! :)
