### ISSUE TITLE
"just stopped working"

### ISSUE THREAD

**Issue by ashleedawg** [wildskyf/personal-blocklist#14]
Worked great until yesterday, now suddenly the block button doesn't appear under search results.

Tried disable/enable, reboot, etc.  Windows Update and Firefox update are turned off so that's not the issue.

Anyone else have this problem?

_(This is my 1st git issue report, sry if this isn't correct procedure.)_

**Comment by wildskyf** [comment]
oh, some users also mentioned that at the review on AMO. So maybe there is really something wrong.
Could you please provide your Firefox version, which would help me to trace/reproduce the problem you faced.

**Comment by wildskyf** [comment]
Hi all my users,

I just published a new version of this add-on(v2.2.0), which would find your block link back.
Update and see whether you can block from Google Search Result List now!

**Comment by wildskyf** [comment]
If you still have this problem, feel free to reopen this issue!
(and remember to mention your environment detail, such as OS version, Firefox version... etc when you report)

**Comment by taxen** [comment]
Updated to 2.6.0 and works fine! Thank you!
Please consider [sub domain block function](https://github.com/wildskyf/personal-blocklist/issues/8).

**Comment by wildskyf** [comment]
@taxen 
I am planning to make the matching function become 'match substring'. Detail will be in #8. :)
