### ISSUE TITLE
Reduce permissions required to only google domains

### ISSUE THREAD

**Issue by flonou** [wildskyf/personal-blocklist#17]
The plugin seems to ask for a lot of permissions, especially every website visited. Could it be reduced to only google domain if possible ?
see : https://github.com/bijij/ViewImage/blob/chrome/manifest.json
which seems to do this

**Comment by Hammedic** [comment]
I essentially came here for this comment. It's an add-on focused only on Google searches, so limit it to Google.

**Comment by wildskyf** [comment]
Thanks for your pull request, @flonou 
I used to don't like the long long list in manifest.
But users does care the permission add-ons ask, so list all domain belonged to google is better.

Thank you. :) And also thank all users for raising your hand. :)

**Comment by wildskyf** [comment]
ref #23
