### ISSUE TITLE
New option with double links

### ISSUE THREAD

**Issue by taxen** [wildskyf/personal-blocklist#18]
Updated to 2.8.0 and disabled the new option.
Now I have every search result with block links of exact same ones.
![image](https://user-images.githubusercontent.com/3875423/39965040-64777862-56cc-11e8-9824-62178bcff0fc.png)

**Comment by wildskyf** [comment]
Thanks for your report!!
I just uploaded a new version v2.8.1, this version should fix this problem.

Sorry that I made this bug... Orz

**Comment by wildskyf** [comment]
Now I am going to close this issue,
If you find this problem is still there, please reopen this issue and leave your Fx version & OS version!

**Comment by taxen** [comment]
Thank you as always! Confirmed it is fixed.
