### ISSUE TITLE
unblock link does not respond

### ISSUE THREAD

**Issue by taxen** [wildskyf/personal-blocklist#19]
I accidentally registered one domain, which includes thousands of individual blog.
I want to cancel the registration, but I have already more than 2000 domains registered in my list.
It takes quite some time to move forward toward the end. Actually, when I push nine times the right arrow, the page moves back to 121-140 from 161-180 and then moves to 181-200. Then I cannot go any further. While doing so, the memory consumption of firefox (freshly started with only this report page open and the add-on option box) goes up as high as 3.5GB and it crashes in the end. Strangely, when I push the right arrow, it sometimes jumps back toward front like 181-200 to suddenly 121-140.
The entry I want to remove should be in the page of 261-280 and I cannot reach there.

The only way to remove directly the link is at the Google search page. But, as you see, when I try to push the link (squared in light blue), the link does not function to remove the domain. It just does not respond.
![70](https://user-images.githubusercontent.com/3875423/40054339-75c4ea6e-587f-11e8-8080-7a48c935850c.png)

Would it be better if we have option to remove all the registered domains at once, and re-register with newly edited domains (of course after carefully back up the current one by using export function), so that we can edit wrongly registered domain more easily?

So, the issues here are:
1. The right arrow (circled in red) does not function correctly, especially after nine pushes or so. The action uses much memory.
![72](https://user-images.githubusercontent.com/3875423/40054610-6bec033c-5880-11e8-8a25-1afdb93a7d88.png)
2. Cancel registration link at Google search page does not work.
3. There is no way to remove registered domain easily when it is located at 9 or later page.

Edit: The way I look at it, the page movement goes back to halfway. For example, when I push the right arrow on 201-220, it once goes back to 81-100, and then goes forward to 221-240, where it should go directly. And this time period takes longer and longer as the page number goes up. It takes more than a whole minute to move from 241-260 to 261-280.

**Comment by wildskyf** [comment]
@taxen the unblockLink should work in the latest version, which I just uploaded.

Please try it and check whether it works or not. :)

**Comment by wildskyf** [comment]
it works when I click it, so I am closing this issue.

About the problem 2 & 3, let's discuss in #31

**Comment by taxen** [comment]
This time, the link to un-register appears correctly and works fine!
Thank you!

**Comment by taxen** [comment]
This time, the link to un-register appears correctly and works fine!
Thank you!

I think this solves my problem #2, not #1.
So... #1 and #3 remain, right?

**Comment by taxen** [comment]
This time, the link to un-register appears correctly and works fine!
Thank you!

I think this solves my problem 2, not 1.
So... 1 and 3 remain, right?
