### ISSUE TITLE
下一頁功能失效

### ISSUE THREAD

**Issue by J4X0N** [wildskyf/personal-blocklist#2]
如題，請求修正，感謝！

**Comment by wildskyf** [comment]
嗨 @J4X0N 
想問你是指哪裡的下一頁功能失效？彈出的 panel 裡面的嗎？截得到圖嗎？
（雖然彈出視窗好像不好截圖）

**Comment by J4X0N** [comment]
@wildskyf 是的！彈出的視窗裡，封鎖清單太多，切換分頁按鈕沒作用

http://imgur.com/a/ikU5Z

**Comment by wildskyf** [comment]
收到，之後來修正～

**Comment by J4X0N** [comment]
@wildskyf thx!!!!

**Comment by wildskyf** [comment]
預計在 1.0.7 會修正，請等待審核過之後升級確認～

**Comment by wildskyf** [comment]
上線囉

**Comment by J4X0N** [comment]
@wildskyf 謝謝sky大！！！
