### ISSUE TITLE
Block link looks too similar to More results link

### ISSUE THREAD

**Issue by endolith** [wildskyf/personal-blocklist#22]
I'm used to clicking the "More results from this site" link under search results, but the "Block this site" link added by this addon looks identical and is in the same place, so I've clicked it accidentally and blocked legitimate sites.  Can you change the style/placement a bit?

![image](https://user-images.githubusercontent.com/58611/43596350-101063fe-964d-11e8-8f5b-2dc0c4b4787f.png)

**Comment by wildskyf** [comment]
thanks for reporting!
This problem has been fixed in version 2.15.0. :)

here is now how it looks like:
<img width="661" alt="2018-11-06 22 31 36" src="https://user-images.githubusercontent.com/6042803/48070823-bd1f4800-e213-11e8-8f29-1ab9b772a670.png">

hope you like it. :)
