### ISSUE TITLE
Minor Code Suggestion

### ISSUE THREAD

**Issue by erosman** [wildskyf/personal-blocklist#29]
The current code is fine. 

Just for code economy these are also possible ....

Example:
```
Array.from(searchResultList).map( searchResultBlock => {
  return serp.alterSearchResultNode_(searchResultBlock)
});
```

You can use the ES6 spread
```
[...searchResultList].map( searchResultBlock => {
  return serp.alterSearchResultNode_(searchResultBlock)
});
```

Since you are not creating a return array from map, `forEach` will do fine
The `return` can also be omitted (in this case)

```
[...searchResultList].fopreach(searchResultBlock => serp.alterSearchResultNode_(searchResultBlock));
// or 
[...searchResultList].fopreach(item => serp.alterSearchResultNode_(item));

```
Alternatively, using `Array.from()` , it has already got a mapping function built in
```
Array.from([1, 2, 3], x => x + x); // example
Array.from(searchResultList, searchResultBlock => serp.alterSearchResultNode_(searchResultBlock);

// the name of the viable in function doesn't really matter, so it is possible to write
Array.from(searchResultList, item => serp.alterSearchResultNode_(item));
```

**Comment by wildskyf** [comment]
Hi Erosman,

Glad to see you here. Thank you for your suggestions! I will refactor this
add-on later. I believe these change would make this add-on more reliable
or readable.

It is welcomed to mention more suggestions, feel free to point out if you
find any. ;)

Good day / Good night,
Wildsky


erosman <notifications@github.com>於 2018年10月7日 週日，18:30寫道：

**Comment by wildskyf** [comment]
When reading it in detail, I just found this feature of ES6 is so cool... Thank you for letting me know!
