### ISSUE TITLE
Next page button in popup window does not work correctly

### ISSUE THREAD

**Issue by wildskyf** [wildskyf/personal-blocklist#31]
as @taxen said in #19, there are some bugs about the next page button.

> I accidentally registered one domain, which includes thousands of individual blog.
I want to cancel the registration, but I have already more than 2000 domains registered in my list.
It takes quite some time to move forward toward the end. Actually, when I push nine times the right arrow, the page moves back to 121-140 from 161-180 and then moves to 181-200. Then I cannot go any further. While doing so, the memory consumption of firefox (freshly started with only this report page open and the add-on option box) goes up as high as 3.5GB and it crashes in the end. Strangely, when I push the right arrow, it sometimes jumps back toward front like 181-200 to suddenly 121-140.
The entry I want to remove should be in the page of 261-280 and I cannot reach there.

> The only way to remove directly the link is at the Google search page. But, as you see, when I try to push the link (squared in light blue), the link does not function to remove the domain. It just does not respond.
![70](https://user-images.githubusercontent.com/3875423/40054339-75c4ea6e-587f-11e8-8080-7a48c935850c.png)

> Would it be better if we have option to remove all the registered domains at once, and re-register with newly edited domains (of course after carefully back up the current one by using export function), so that we can edit wrongly registered domain more easily?

> So, the issues here are:
> 1. The right arrow (circled in red) does not function correctly, especially after nine pushes or so. The action uses much memory.
![72](https://user-images.githubusercontent.com/3875423/40054610-6bec033c-5880-11e8-8a25-1afdb93a7d88.png)
> 2. Cancel registration link at Google search page does not work.
> 3. There is no way to remove registered domain easily when it is located at 9 or later page.

> Edit: The way I look at it, the page movement goes back to halfway. For example, when I push the right arrow on 201-220, it once goes back to 81-100, and then goes forward to 221-240, where it should go directly. And this time period takes longer and longer as the page number goes up. It takes more than a whole minute to move from 241-260 to 261-280.

**Comment by taxen** [comment]
Not to make you any more busy than you are, but the situation is the same after updating to 2.15.0.
Just to let you know.

**Comment by wildskyf** [comment]
@taxen no worry, this issue is still open because that problem is not mark as solved. :)

**Comment by wildskyf** [comment]
@taxen hi, I just release v3.2.0, are you willing to update to it and check it whether this issue is solved?

**Comment by taxen** [comment]
@wildskyf Sorry for delayed response. I just tested on my current profile after updating to 2.15.2. It now has 4900 entries. When I move the list forward, the response slows down like before. It significantly delays around 201-220. When trying to move from 221-240 directly to 241-260, it actually move back once to 41-60, which took about 33 seconds, and then move to 241-260, which took another 66 seconds. During the procedure, the memory usage moves up to 7.8 GB from 6.5 GB at the beginning. I will test on a new profile, but I am in the middle of something. So it would take some time for the report.

Oh, I need to stick with FF prior to 57.0 for other add-ons. You change to 3.1.0 and 3.2.1 cannot be done to v2.x?

**Comment by taxen** [comment]
@wildskyf In the meantime, I just tested on Waterfox 56.2.14 (64bit). When tried to update to 3.2.1, a warning (unable to function or something) came up, but installed anyway. I see what changed in v3.x. It looks fine to work to me. I imported the 4900 entries and moved back and forth with ease. If only this could work on my old FF (prior to 57.0).

**Comment by wildskyf** [comment]
@taxen latest version,v3.3.0, just released. I am currently rewriting all code of the this add-on, so there is no plan to continue supporting v2.x. Therefore I make the min_strict_version to 53.0, is it enough low for you to install in your FF (prior to 57.0)?

and about your slowdown problem, hmm... that is so strange that the time it takes and memory it use is so terrible. I currently have no idea what happened... maybe I will test the case with extremely large amount of data when rewriting back-end functions.

**Comment by wildskyf** [comment]
And about test in a new profile, take your time. :)
Thanks for your waiting for my delayed (so long) fixing process...

**Comment by taxen** [comment]
@wildskyf Yay! Yes, 53.0 is enough low for my FF. I use 56.0.2, which is the latest for the old add-ons.

After updating to 3.3.0, it works fine on my FF! Thank you so much!

To avoid confusion, memory usage above mentioned is the whole memory usage including other running applications. So only the gap is relevant, about 1.3 GB increase.

If you need huge list, I have 4900 entries list. Please just ask me and I will mail it to you.

**Comment by taxen** [comment]
@wildskyf Since 3.3.0 also works on old FFs, it solved my problem to say the least. So, as far as I am concerned, you could close the issue.

One more feature request, though, is... direct page navigation box so as to quickly move to a target page. My list shows as many as 245 pages. It is still hard to reach out to page 120 by pushing ">" as many as 119 times or "6" "8" "10"... nearly 60 times.

Maybe... filtering function would be convenient as one way to reach a target quickly. In my usage, I already know the whole domain which I want to remove.

**Comment by wildskyf** [comment]
yeah, [filtering function](https://github.com/wildskyf/personal-blocklist/issues/37) will be implement in the [near future](https://github.com/wildskyf/personal-blocklist/milestone/3).

I will also think about `direct page navigation box`. Thanks :)

**Comment by wildskyf** [comment]
The next page button in popup window seems work correctly. Let’s close this issue. :)
