### ISSUE TITLE
Block list is too many to show the list.

### ISSUE THREAD

**Issue by SyaoranChang** [wildskyf/personal-blocklist#32]
Hi,

I add this list sits
https://github.com/Feiox/useless-websites/blob/master/domains.csv
and then block list is too many to show the list.

Personal Blocklist (not by Google) 2.15.0
Firefox 63.0.3

**Comment by wildskyf** [comment]
you seems to face the same problem as @taxen face...
ref: #31

**Comment by SyaoranChang** [comment]
Hi
Today I enable this addon and try click to open the list.
It take less than 1s to show the list.
Seems the issue is fixed.

I have another feature I want, can I search the list to find the website I want to allow?
Or How to delete all site that I can re-add list again?

**Comment by wildskyf** [comment]
Glad to hear that, so we could happily close this issue. :D

And I plan to implement search function in manage page in the near future.
Here is the ticket link:
https://github.com/wildskyf/personal-blocklist/issues/37
