### ISSUE TITLE
Preference to remove "Block domain.com" from search results

### ISSUE THREAD

**Issue by DaveJarvis** [wildskyf/personal-blocklist#9]
**Feature Request**
Add a preference to disable adding the hyperlink to the search results page to quickly block sites.

**Replicate**
1. Search Google for **test**.
1. Search results include **Block speedtest.net**.

**Expected Results**
Search results do not contain a hyperlink to block speedtest.net.

**Actual Results**
Search results contain a hyperlink.

**Comment by wildskyf** [comment]
Hi @DaveJarvis and @recardograca
I just uploaded the new version v2.8.0, in which you could go to preference page to toggle the option `disable the "Block domain.com" in search result.`. It should fit your Feature Request!

Thanks for your request, which made this add-on better and better. :)
Enjoy it!

Feel free to reopen this issue if you got any problem about this feature.
